# Dependencies
markdown:         redcarpet
highlighter:      pygments
encoding:         UTF-8

# Permalinks
permalink:        pretty

# Setup
title:            Bastiaan Quast
tagline:          Replicable Development Economics using R and Git 
description:      'A personal blog about Replicable Development Economics using R and Git'
url:              http://qua.st/
baseurl:          '/'
paginate:         5

author:
  name:           'Bastiaan Quast'
  url:            https://twitter.com/baquast

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bquast/bquast.github.io

exclude:          [rmarkdown]

profiles_list:
  ORCID:   'http://orcid.org/0000-0002-2951-3577'
  GitHub:  'http://github.com/bquast'
  Google+: 'https://plus.google.com/+BastiaanQuast'
  Twitter: 'https://twitter.com/baquast'
