# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            bquast.github.io
tagline:          R visualisations, R packages, and Development Economics
description:      'nothing here yet'
url:              http://bquast.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Bastiaan Quast'
  url:            https://twitter.com/baquast

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bquast/bquast.github.io
