---
title: "Neural Network IV with Simulated Data"
output: html_document
permalink: neural-network-iv-simulated
tags: [R, linear model, neural network]
---

Some simulated data, borrowed from [this post](http://jacobsimmering.com/2014/01/10/InstrumentalVariables.html).

```{r data}
# library for generation multivariate distributions
library(MASS)

# always use the same random numbers
set.seed(123)

# the means and errors for the multivariate distribution
MUs    <- c(10,15)
SIGMAs <- matrix(c(1,   0.5,
                   0.5, 2   ),
                 nrow=2,
                 ncol=2       )

# the multivariate distribution
mdist <- mvrnorm(n     = 1000,
                 mu    = MUs,
                 Sigma = SIGMAs)

# create unobserved covariate
c <- mdist[ , 2]

# create the instrumental variable
z <- rnorm(1000)

# create observed variable
x <- mdist[ , 1] + z

# constuct the dependent variable
y <- 1 + x + c + rnorm(1000, 0, 0.5)
```

Check if the variables behave as expected

```{r checks}
cor(x, c)
cor(z, c)
```

Let's look at the true model.

```{r true}
lm(y ~ x + c)
```

Estimate using OLS.

```{r ols}
lm(y ~ x)
```

Now using instrumental variables.

```{r, message=FALSE}
library(AER)
ivreg(y ~ x | z)
```

Now using the `lm` function.

```{r}
# first stage
lms1 <- lm(x ~ z)

# manually obtain fitted values
lmXhat <- lms1$coefficients[2]*z + lms1$coefficients[1]

# estimate second stage using Xhat
(lms2 <- lm(y ~ lmXhat) )
```

Now we can do the same using a neural network

```{r}
library(nnet)

# first stage
nns1 <- nnet(x ~ z, size=0, skip=TRUE, linout=TRUE)

# manually obtain fitted values
nnXhat <- nns1$fitted.values

# estimate second stage using Xhat
nns2 <- nnet(y ~ nnXhat, size=0, skip=TRUE, linout=TRUE)
summary(nns2)
```

Compare output.

```{r}
lms2$coefficients - nns2$wts
```

Compare estimates.

```{r qplot, message=FALSE}
library(ggplot2)
qplot(lms2$fitted.values - nns2$fitted.values)
```

Now redo using a non-linearity
