---
layout: post
title: ggvis, shiny, and HTML5 slides
permalink: ggvis-shiny-html5-slides
---
[Sepal-Modeling](http://bquast.shinyapps.io/Iris-App) is a **shiny app**,
which uses **ggvis** to fit LOESS smoothers on the sepal ratios of the **iris** dataset.
There are separate smoothers  for every species, as well as a general smoother for all observations.
The span can be adjusted in order to see if we need to model the sepal ratio per species or jointly.

There is also an [HTML5 **dynamic** presentation](http://bquast.shinyapps.io/Iris-Presentation) ([code](https://github.com/bquast/Iris-Presentation/blob/master/dynamic.Rmd) )
and a [HTML5 **static** presentation](http://bquast.github.io/Iris-Presentation), both build using **rmarkdown v2**.

The code in the presentation is most straight forward, it uses only ggvis code for the interactivity.


{% highlight r %}
# load the ggvis package
library(ggvis)
{% endhighlight %}



{% highlight text %}
## The ggvis API is currently rapidly evolving. We strongly recommend that you do not rely on this for production, but feel free to explore. If you encounter a clear bug, please file a minimal reproducible example at https://github.com/rstudio/ggvis/issues. For questions and other discussion, please use https://groups.google.com/group/ggvis.
## 
## Attaching package: 'ggvis'
## 
## The following object is masked from 'package:stats':
## 
##     filter
{% endhighlight %}



{% highlight r %}
# load the dplyr package
# for use of magrittr pipe: %>%
library(dplyr)
{% endhighlight %}



{% highlight text %}
## 
## Attaching package: 'dplyr'
## 
## The following objects are masked from 'package:stats':
## 
##     filter, lag
## 
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
{% endhighlight %}



{% highlight r %}
# lazyload the dataset and pass it to
iris %>%
  # the ggvis function, now set the axis
  ggvis(~Sepal.Width, ~Sepal.Length) %>%
  # add the smoother for all points
  layer_smooths(span = input_slider(0.5, 1, 0.5,
                                    label = 'General Model'),
                se = TRUE) %>%
  # now group by species
  group_by(Species) %>%
  # add points per species and colour them
  layer_points(size := input_slider(10, 200, 50,
                                    label = 'Point Size'),
               opacity := input_slider(0.5, 1, 0.5,
                                       label = 'Point Opacity'),
               fill = ~Species) %>%
  # now add smoothers per species and colour them
  layer_smooths(span = input_slider(0.5, 1, 0.5, label = 'Species Models'), fill = ~Species, se=TRUE) %>%
  # add new labels
  add_axis("x", title = "Sepal Width") %>%
  add_axis("y", title = "Sepal Length") %>%
  # finally declare as shiny object
  bind_shiny("ggvis", "ggvis_ui")
{% endhighlight %}



{% highlight text %}
## Error: bind_shiny() must be run inside a shiny app.
{% endhighlight %}

